version: 2.1

orbs:
  node: circleci/node@5.0.2

executors:
  basic:
    docker:
      - image: 'cimg/node:lts'
    resource_class: small

  playwright:
    docker:
      - image: mcr.microsoft.com/playwright:v1.24.2-focal
    environment:
      NODE_ENV: development
    resource_class: medium

commands:
  setup_github_packages:
    description: Setup environment to access Github Packages
    steps:
      - run:
          name: 'Add npm registry to .npmrc'
          command: 'echo //npm.pkg.github.com/:_authToken=${BOT_GITHUB_TOKEN} >> ~/.npmrc'

jobs:
  test_a11y:
    description: 'Testing: a11y'
    executor: playwright

    steps:
      - checkout
      - setup_github_packages
      - node/install-packages

      - run:
          name: 'Generate a11y tests'
          command: 'npm run test:a11y:generate'
      - run:
          name: 'Run a11y tests'
          command: 'PLAYWRIGHT_JUNIT_OUTPUT_NAME=./__tests__/_test-results/junit/ci-a11y-results.xml npm run test:a11y'

      - store_test_results:
          path: ./__tests__/_test-results/junit/ci-a11y-results.xml

  test_e2e:
    description: 'Testing: End-to-end'
    executor: playwright

    steps:
      - checkout
      - setup_github_packages
      - node/install-packages

      - run:
          name: 'Run end-to-end tests'
          command: 'PLAYWRIGHT_JUNIT_OUTPUT_NAME=./__tests__/_test-results/junit/ci-e2e-results.xml npm run test:e2e'

      - store_test_results:
          path: ./__tests__/_test-results/junit/ci-e2e-results.xml

  build_package:
    description: 'Build the JavaScript package'
    executor: basic

    steps:
      - checkout
      - setup_github_packages
      - node/install-packages

      - run:
          name: 'Rollup build'
          command: 'npm run build'

      - store_artifacts:
          path: _dist

workflows:
  version: 2
  testing:
    jobs:
      - test_a11y:
          context: design-systems-automation
          filters:
            branches:
              ignore:
                - main
            tags:
              ignore: /.*/
      - test_e2e:
          context: design-systems-automation
          filters:
            branches:
              ignore:
                - main
            tags:
              ignore: /.*/
      - build_package:
          context: design-systems-automation
          filters:
            tags:
              only:
                - /^v.*/
            branches:
              ignore: /.*/
