name: Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - feature/DS-374--published-storybook
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  packages: read

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install and Build
        run: |
          echo //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }} >> ~/.npmrc
          npm install
          npm run storybook:build
      # Publish site to github-pages.
      - name: Publish to pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: storybook-static
